name: CI/CD Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs: 
   test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      
      - name: Install dependencies
        run: npm install
      
      - name: Run tests
        run: npm run check    

  deploy:
    needs: test
    runs-on: self-hosted
    
    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v3    
      
      
      - name: Install dependencies
        run: npm install
      - name: Run the Application By PM2
        run: |
          ls -a
          pm2 status

          #delete node-App
          pm2 delete node-App || true

          #create node-App
          pm2 start "npm start" --name "node-app" 

          #Save the Process PM2
          pm2 save 
             